server:
  port: 10002 #服务端口
spring:
  application:
    name: cloudConfig #指定服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yaopj4520/config-repo.git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lamb
    password: lamb
    virtualHost: lambVH
management:
    endpoints:
      web:
        exposure:
          include: bus-refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #spring.cloud.client.ip-address:获取ip地址